### ISSUE TITLE
'Sending RECEIVE_PRINTER_JOB queue: raw' then no print

### ISSUE THREAD

**Issue by AndrewBarber** [Atlantis-Software/node-lpr#1]
Hi there,

Thank you for this package. 
We are trying to use this to print a buffer however using the example code we can't get it to print to our printer.

Using the example code we see the following in the console..
```
Connected to localhost:631
Sending RECEIVE_PRINTER_JOB queue: raw
Connection closed
```

However, there is no print, with no real error. 

We are using RaspbianOS and have tried on MacOS.

**Comment by atiertant** [comment]
hi, did you tried configure lpr on a computer and send a test page ? are you sure raw is the queue ?
what does your buffer contain ? the content is specific to all printer
